Repository WildCodeSchool/orleans-0918-php-cestmamaison, pull requests merged in 2018-11, with the labels that each got.

#180 PR fix de la navbar
  public/assets/css/styles.css
  public/assets/images/image_banniere.jpg
  public/assets/js/agency.js
  src/View/Visitor/header.html.twig
Labels: Reviewed by PO

#181 Sprint4 us13
  app/db.php.dist
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Service/DropdownService.php
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/header.html.twig
Labels: Conflicts, Reviewed by PO

#183 en cours
  src/View/Admin/brand/index.html.twig
Labels: Reviewed by PO

#184 redirection apres les ajouts et modifications
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
Labels: Reviewed by PO

#186 Dev
  app/db.php.dist
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  public/assets/images/CategoryImages/image5bd0d55feb0cb.n
  public/assets/images/CategoryImages/image5bd1ac1d5aa90.p
  public/assets/images/image_banniere.jpg
  public/assets/js/agency.js
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/ProductController.php
  src/Model/Product.php
  src/Model/ProductManager.php
  src/Service/DropdownService.php
  src/View/Admin/Product/index.html.twig
  src/View/Admin/Product/update.html.twig
  src/View/Admin/Product/update_form.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/header.html.twig
Labels: Reviewed by PO

#187 Merge pull request #177 from WildCodeSchool/dev
  src/View/Visitor/footer.html.twig
Labels: Reviewed by PO

#185 Pr fix category and products
  src/Model/ProductManager.php
Labels: Changes Requested, Corrections Done, Reviewed by PO

#188 affichage des images sur l'index
  public/assets/css/styleAdmin.css
  src/View/Admin/Category/index.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/base.html.twig
Labels: Reviewed by PO

#189 Prfixe banniere
  public/assets/css/styles.css
  public/assets/images/presentationBanniere.jpeg
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#190 Dev
  public/assets/css/styleAdmin.css
  public/assets/css/styles.css
  public/assets/images/presentationBanniere.jpeg
  src/Model/ProductManager.php
  src/View/Admin/Category/index.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Visitor/footer.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
  src/View/base.html.twig
Labels: Reviewed by PO

#179 fonctionnalite mise en avant des produits
  app/routing.php
  src/Controller/ProductController.php
  src/Model/Product.php
  src/Model/ProductManager.php
  src/View/Admin/Product/index.html.twig
Labels: Conflicts, Corrections Done, Reviewed by PO

#192 rajout de colonne dans le dropdown
  public/assets/css/styles.css
Labels: Changes Requested, Corrections Done, Reviewed by PO

#193 Highlighted brands on homepage
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/index.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#195 Footer modifié
  public/assets/css/styles.css
  public/assets/images/facebook.png
  src/View/Visitor/footer.html.twig
Labels: Reviewed by PO

#196 Page des produits en fonction d'une marque
  app/routing.php
  public/assets/css/styles.css
  src/Model/ProductManager.php
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#199 Pr fix contact
  src/Controller/HomeController.php
Labels: Reviewed by PO

#200 Prfixe style nav bar
  public/assets/css/styles.css
  src/View/Visitor/header.html.twig
Labels: Reviewed by PO

#201 changement police des cards
  public/assets/css/styles.css
  public/assets/images/BrandImages/.gitkeep
  public/assets/images/CategoryImages/.gitkeep
Labels: Reviewed by PO

#202 Dev to master
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/BrandImages/.gitkeep
  public/assets/images/CategoryImages/.gitkeep
  src/Controller/HomeController.php
  src/Model/ProductManager.php
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/header.html.twig
Labels: Reviewed by PO

#203 Modification rooting
  app/routing.php
  src/View/Admin/Product/index.html.twig
Labels: Reviewed by PO

#204 Produit en avant sur la page d'acceuil visiteur
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#205 effet hover cards index
  public/assets/css/styles.css
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#206 Prfix homepage1er paragraphe
  public/assets/css/styles.css
  public/assets/images/nounoursbackground.jpeg
  src/View/Visitor/index.html.twig
  src/View/base.html.twig
Labels: Corrections Done, Reviewed by PO

#207 Showproduct
  app/routing.php
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Admin/brand/index.html.twig
  src/View/Visitor/Product/show.html.twig
Labels: Reviewed by PO

#210 Pr fix w3 c
  public/assets/css/styles.css
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
  src/View/Visitor/layout.html.twig
Labels: Reviewed by PO

#208 Prfixe style home
  public/assets/css/styles.css
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
Labels: Corrections Done, Reviewed by PO

#209 Dev to master apres les PR show et PR-FIX accepter
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/nounoursbackground.jpeg
  src/Controller/HomeController.php
  src/View/Admin/Product/index.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/Product/show.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
  src/View/Visitor/layout.html.twig
  src/View/base.html.twig
Labels: Reviewed by PO

#211 rectification CSS
  public/assets/css/styles.css
Labels: Reviewed by PO

#212 Ajout du block endfor oublier dans twig
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#213 Dev
  public/assets/css/styles.css
Labels: Reviewed by PO

#214 Prfix index
  public/assets/css/styles.css
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#215 ajout des icons contact et carte
  src/View/Visitor/Contact/index.html.twig
Labels: Reviewed by PO

#216 Errors corrigée
  app/routing.php
  public/assets/images/ProductImages/.gitkeep
  src/Controller/BrandController.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Admin/headerAdmin.html.twig
Labels: Reviewed by PO

#219 Reparation upd
  public/assets/css/styles.css
  src/Controller/ProductController.php
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#224 Pr fixe acceuil
  public/assets/css/styles.css
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#225 Dev
  public/assets/css/styles.css
  public/assets/images/CategoryImages/categoryJouet.jpeg
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#226 Pr fix vignettes
  public/assets/css/styles.css
Labels: Reviewed by PO

#229 correction cards
  public/assets/css/styles.css
  src/View/Visitor/index.html.twig
Labels: Conflicts

#231 Dernier fix
  public/assets/css/styles.css
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
Labels: Reviewed by PO

#233 nouveau dernier fix
  public/assets/css/styles.css
  public/assets/images/BrandImages/.gitkeep
  public/assets/images/BrandImages/image5bd017c103873.jpeg
  public/assets/images/BrandImages/image5bd017ce15b90.jpeg
  public/assets/images/BrandImages/image5be1bcc4e09fe.jpeg
  public/assets/images/BrandImages/image5be1bcdd11703.jpeg
  public/assets/images/CategoryImages/.gitkeep
  public/assets/images/CategoryImages/categoryJouet.jpeg
  public/assets/images/ProductImages/.gitkeep
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#232 derniere dev to master
  public/assets/css/styles.css
  public/assets/images/BrandImages/.gitkeep
  public/assets/images/CategoryImages/.gitkeep
  public/assets/images/CategoryImages/categoryJouet.jpeg
  public/assets/images/ProductImages/.gitkeep
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO
