Repository WildCodeSchool/orleans-0918-php-cestmamaison, pull requests merged in 2018-10, with the labels that each got.

#26 Template
  public/assets/bootstrap/css/bootstrap.css.map
  public/assets/bootstrap/css/bootstrap.min.css
  public/assets/bootstrap/css/bootstrap.min.css.map
  public/assets/bootstrap/js/bootstrap.bundle.js
  public/assets/bootstrap/js/bootstrap.bundle.js.map
  public/assets/bootstrap/js/bootstrap.bundle.min.js
  public/assets/bootstrap/js/bootstrap.bundle.min.js.map
  public/assets/bootstrap/js/bootstrap.js
  public/assets/bootstrap/js/bootstrap.js.map
  public/assets/bootstrap/js/bootstrap.min.js
  public/assets/bootstrap/js/bootstrap.min.js.map
  public/assets/css/bootstrap.css
  public/assets/css/styles.css
  public/assets/images/cestmamaison-1.png
  public/assets/jquery-easing/jquery.easing.compatibility.js
  public/assets/jquery-easing/jquery.easing.js
  public/assets/jquery-easing/jquery.easing.min.js
  public/assets/js/agency.js
  public/assets/js/agency.min.js
  public/assets/js/contact_me.js
  public/assets/js/contact_me.min.js
  public/assets/js/jqBootstrapValidation.js
  public/assets/js/jqBootstrapValidation.min.js
  src/View/base.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Changes Requested

#25 Sprint1 us15
  app/routing.php
  src/Controller/AdminController.php
  src/Controller/ItemController.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/View/Admin/contentAdmin.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Admin/layoutAdmin.html.twig
  src/View/Item/base.html.twig
  src/View/layout.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#28 Merge Dev qui contient l'US15
  app/routing.php
  src/Controller/AdminController.php
  src/Controller/ItemController.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/View/Admin/contentAdmin.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Admin/layoutAdmin.html.twig
  src/View/Item/base.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#29 Sprint1 US4 Footer: création du footer
  public/assets/css/styles.css
  public/assets/images/icone-facebook.png
  public/assets/images/kisspng-computer-icons-facebook-inc-facebook-icon-5afd43bb4db839.4384131915265473873183 (1).png
  public/assets/images/kisspng-facebook-icon.png
  src/View/base.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Changes Requested, Reviewed by PO

#32 Sprint1 us17
  app/routing.php
  src/Controller/AdminController.php
  src/Controller/CategoryController.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/ItemManager.php
  src/View/Admin/Category/_form.html.twig
  src/View/Admin/Category/add.html.twig
  src/View/Admin/Homepage/contentAdmin.html.twig
  src/View/Admin/contentAdmin.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Admin/layoutAdmin.html.twig
Labels: Corrections Done, Reviewed by PO

#33 Dev
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/icone-facebook.png
  public/assets/images/kisspng-computer-icons-facebook-inc-facebook-icon-5afd43bb4db839.4384131915265473873183 (1).png
  public/assets/images/kisspng-facebook-icon.png
  src/Controller/AdminController.php
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
  src/Model/Brand.php
  src/Model/BrandManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/ItemManager.php
  src/View/Admin/Category/_form.html.twig
  src/View/Admin/Category/add.html.twig
  src/View/Admin/Homepage/contentAdmin.html.twig
  src/View/Admin/brand/_form.html.twig
  src/View/Admin/brand/add.html.twig
  src/View/Admin/contentAdmin.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Admin/layoutAdmin.html.twig
  src/View/base.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#34 Résolution des bugs
  app/routing.php
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
Labels: Reviewed by PO

#35 Dev -> master
  app/routing.php
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
Labels: Reviewed by PO

#83 Pull Request bouton Dropdown Marques
  src/View/header.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#94 Suppression du padding qui faisait un trait blanc en dessous du footer
  public/assets/css/styles.css
Labels: Reviewed by PO

#95 Rajout des images pour la partie acceuil visiteur
  public/assets/images/banniere.jpg
  public/assets/images/jouet-cube.jpg
Labels: Reviewed by PO

#96 Dev
  app/routing.php
  public/assets/css/styleAdmin.css
  public/assets/css/styles.css
  public/assets/images/banniere.jpg
  public/assets/images/jouet-cube.jpg
  src/Controller/HomeController.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/Service/DropdownService.php
  src/View/Visitor/index.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#89 Sprint2 us22
  app/routing.php
  src/Controller/BrandController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/View/Admin/Homepage/contentAdmin.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/base.html.twig
Labels: Corrections Done, Reviewed by PO

#88 Sprint2 us16
  app/routing.php
  src/Controller/CategoryController.php
  src/View/Admin/Category/index.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
Labels: Changes Requested, Reviewed by PO

#92 SPRINT02-US34
  public/assets/css/styleAdmin.css
  public/assets/images/CategoryImages/image5bc858f341737.jpeg
  src/Controller/CategoryController.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/_form.html.twig
Labels: Corrections Done, Reviewed by PO

#85 Sprint2 us8
  app/routing.php
  public/assets/css/bootstrap.css
  public/assets/css/styles.css
  public/assets/images/background.jpg
  public/assets/images/boutique_ext.jpg
  public/assets/images/boutique_int1.jpeg
  public/assets/images/boutique_int2.jpeg
  public/assets/images/cube.jpg
  public/assets/images/voiturebois.jpg
  src/Controller/HomeController.php
  src/View/Visitor/Presentation/index.html.twig
  src/View/Visitor/footer.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/layout.html.twig
  src/View/layout.html.twig
Labels: Conflicts, Corrections Done, Reviewed by PO

#91 Sprint2us26
  app/routing.php
  src/Controller/ProductController.php
  src/Model/Product.php
  src/Model/ProductManager.php
  src/View/Admin/Product/delete.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/Product/show.html.twig
Labels: Conflicts, Corrections Done, Reviewed by PO

#98 Dev
  app/routing.php
  public/assets/css/bootstrap.css
  public/assets/css/styleAdmin.css
  public/assets/css/styles.css
  public/assets/images/CategoryImages/image5bc858f341737.jpeg
  public/assets/images/background.jpg
  public/assets/images/boutique_ext.jpg
  public/assets/images/boutique_int1.jpeg
  public/assets/images/boutique_int2.jpeg
  public/assets/images/cube.jpg
  public/assets/images/voiturebois.jpg
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/ProductController.php
  src/Model/AbstractManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/Product.php
  src/Model/ProductManager.php
  src/View/Admin/Category/_form.html.twig
  src/View/Admin/Category/index.html.twig
  src/View/Admin/Homepage/contentAdmin.html.twig
  src/View/Admin/Product/delete.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/Product/show.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Admin/headerAdmin.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/Presentation/index.html.twig
  src/View/Visitor/footer.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/layout.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#99 Prfix sprint2us26
  src/View/Admin/headerAdmin.html.twig
Labels: Reviewed by PO

#100 Dev
  src/View/Admin/headerAdmin.html.twig
Labels: Reviewed by PO

#101 Prfixe admin category
  src/View/Admin/Category/index.html.twig
Labels: Reviewed by PO

#112 Bouton Upload
  public/assets/images/BrandImages/image5bcee7d92bd7b.png
  src/Controller/BrandController.php
  src/Model/Brand.php
  src/Model/BrandManager.php
  src/View/Admin/brand/_form.html.twig
  src/View/Admin/brand/add.html.twig
Labels: Reviewed by PO

#123 Pr fix upload category
  src/Controller/CategoryController.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/add.html.twig
Labels: Reviewed by PO

#131 Dev
  public/assets/images/BrandImages/image5bcee7d92bd7b.png
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
  src/Model/Brand.php
  src/Model/BrandManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/add.html.twig
  src/View/Admin/Category/index.html.twig
  src/View/Admin/brand/_form.html.twig
  src/View/Admin/brand/add.html.twig
Labels: Reviewed by PO

#129 Sprint3 us12
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Admin/Category/_form.html.twig
  src/View/Visitor/Contact/index.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#130 Pr fix visitor page
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#141 Dev
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Admin/Category/_form.html.twig
  src/View/Visitor/Contact/index.html.twig
  src/View/Visitor/header.html.twig
  src/View/Visitor/index.html.twig
Labels: Reviewed by PO

#146 Sprint3us29
  app/routing.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Admin/Product/delete.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/Product/show.html.twig
  src/View/base.html.twig
Labels: Corrections Done, Reviewed by PO

#148 SPRINT03-US11 Affichage de tous les produits en fonction d'une catégorie
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/ProductImages/doudou-elephant.jpg
  public/assets/images/ProductImages/doudou-hippo.jpg
  src/Controller/HomeController.php
  src/Model/ProductManager.php
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/header.html.twig
Labels: Reviewed by PO

#152 La page vue n'a apparemment pas été push
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
Labels: Reviewed by PO

#147 Sprint3 us33
  app/routing.php
  public/assets/css/styles.css
  src/Controller/BrandController.php
  src/Model/Brand.php
  src/Model/BrandManager.php
  src/View/Admin/brand/index.html.twig
Labels: Changes Requested, Reviewed by PO

#143 Sprint3 us18
  app/routing.php
  public/assets/images/BrandImages/image5bcee7d92bd7b.png
  public/assets/images/CategoryImages/image5bc858f341737.jpeg
  src/Controller/CategoryController.php
  src/Model/Brand.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/index.html.twig
  src/View/Admin/Category/update.html.twig
  src/View/Admin/Category/update_form.html.twig
Labels: Changes Requested, Corrections Done, Reviewed by PO

#149 Dev
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/BrandImages/image5bcee7d92bd7b.png
  public/assets/images/CategoryImages/image5bc858f341737.jpeg
  public/assets/images/ProductImages/doudou-elephant.jpg
  public/assets/images/ProductImages/doudou-hippo.jpg
  src/Controller/BrandController.php
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/ProductController.php
  src/Model/Brand.php
  src/Model/BrandManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/ProductManager.php
  src/View/Admin/Category/index.html.twig
  src/View/Admin/Category/update.html.twig
  src/View/Admin/Category/update_form.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/Product/show.html.twig
  src/View/Admin/brand/index.html.twig
  src/View/Visitor/Brand/showProductsWithBrand.html.twig
  src/View/Visitor/Category/showProductsWithCategory.html.twig
  src/View/Visitor/header.html.twig
  src/View/base.html.twig
Labels: Reviewed by PO

#155 Sprint4us19
  app/routing.php
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/index.html.twig
Labels: Reviewed by PO

#173 Sprint4us25
  app/routing.php
  src/Controller/BrandController.php
  src/Model/BrandManager.php
  src/View/Admin/brand/index.html.twig
Labels: Reviewed by PO

#154 Sprint us27
  .gitignore
  app/routing.php
  public/assets/images/CategoryImages/image5bd0d55feb0cb.n
  public/assets/images/CategoryImages/image5bd1ac1d5aa90.p
  public/assets/images/ProductImages/doudou-elephant.jpg
  public/assets/images/ProductImages/doudou-hippo.jpg
  src/Controller/AbstractController.php
  src/Controller/ProductController.php
  src/Model/Product.php
  src/Model/ProductManager.php
  src/View/Admin/Product/_form.html.twig
  src/View/Admin/Product/add.html.twig
Labels: Corrections Done, Reviewed by PO
